import ExcelJS from "exceljs";
import type { TechPack } from "@/lib/techpack/schema";

const HEAD_FILL: ExcelJS.Fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF251670" } };
const ALT_FILL: ExcelJS.Fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF1F4F6" } };
const BORDER: Partial<ExcelJS.Borders> = {
  top: { style: "thin", color: { argb: "FFE3E8ED" } },
  bottom: { style: "thin", color: { argb: "FFE3E8ED" } },
  left: { style: "thin", color: { argb: "FFE3E8ED" } },
  right: { style: "thin", color: { argb: "FFE3E8ED" } },
};

function sheet(wb: ExcelJS.Workbook, name: string, rtl: boolean) {
  const ws = wb.addWorksheet(name, {
    views: [{ rightToLeft: rtl, showGridLines: false }],
    pageSetup: { paperSize: 9, orientation: "landscape", fitToPage: true, fitToWidth: 1, fitToHeight: 0 },
  });
  return ws;
}

function title(ws: ExcelJS.Worksheet, text: string, sub?: string) {
  const r = ws.addRow([text]);
  r.font = { bold: true, size: 14, color: { argb: "FF251670" } };
  if (sub) {
    const s = ws.addRow([sub]);
    s.font = { size: 9, color: { argb: "FF6B7280" } };
  }
  ws.addRow([]);
}

function table(ws: ExcelJS.Worksheet, headers: string[], rows: (string | number | null | { formula: string })[][], widths?: number[]) {
  const h = ws.addRow(headers);
  h.eachCell((c) => {
    c.fill = HEAD_FILL;
    c.font = { bold: true, color: { argb: "FFFFFFFF" }, size: 10 };
    c.alignment = { vertical: "middle", wrapText: true };
    c.border = BORDER;
  });
  rows.forEach((row, i) => {
    const r = ws.addRow(row);
    r.eachCell({ includeEmpty: true }, (c) => {
      c.border = BORDER;
      c.alignment = { vertical: "top", wrapText: true };
      c.font = { size: 10 };
      if (i % 2 === 1) c.fill = ALT_FILL;
    });
  });
  if (widths) widths.forEach((w, i) => (ws.getColumn(i + 1).width = w));
  ws.addRow([]);
}

export async function buildPackXlsx(pack: TechPack, lang: "en" | "ar"): Promise<Buffer> {
  const rtl = lang === "ar";
  const wb = new ExcelJS.Workbook();
  wb.creator = "Masdr Tech Pack";
  wb.created = new Date();
  const sizes = pack.sizes.map((s) => s.code);
  const baseIdx = Math.max(0, pack.sizes.findIndex((s) => s.is_base));

  // Cover
  {
    const ws = sheet(wb, "Cover", rtl);
    title(ws, `${pack.header.style_name_en} / ${pack.header.style_name_ar}`, `Tech pack v${pack.meta.version} · ${pack.header.date} · generated by Masdr Tech Pack (${pack.meta.generator.primary_model})`);
    table(
      ws,
      ["Field", "Value"],
      [
        ["Brand", pack.header.brand],
        ["Style number", pack.header.style_number],
        ["Season", pack.header.season],
        ["Category", `${pack.header.category_en} / ${pack.header.category_ar}`],
        ["Product type", `${pack.header.product_type_en} / ${pack.header.product_type_ar}`],
        ["Base size", pack.header.base_size],
        ["Units", "cm, gsm, Tex, SPI"],
        ["Status", pack.header.status],
        ["Description", pack.product.description_en],
        ["الوصف", pack.product.description_ar],
        ["Intended use", pack.product.intended_use_en],
        ["الاستخدام المقصود", pack.product.intended_use_ar],
        ["Fit intent", pack.product.fit_intent_en],
        ["Factory readiness score", `${pack.readiness.score} / 100`],
      ],
      [28, 110],
    );
  }

  // POM spec with regrade formulas: S/L reference the base-size column
  {
    const ws = sheet(wb, "POM_Spec", rtl);
    title(ws, "Measurement specification / جدول القياسات", `All values finished cm. Edit the ${pack.header.base_size} column; other sizes regrade by the stated grade.`);
    const headers = ["Code", "POM (EN)", "POM (AR)", "How to measure", ...sizes, "Tol ±", "Grade", "Derivation", "Source", "Confidence", "Factory comment"];
    const firstDataRow = ws.rowCount + 2; // header row is next
    const rows = pack.poms.map((p, i) => {
      const r = firstDataRow + i;
      const baseCol = colLetter(5 + baseIdx);
      const gradeCol = colLetter(5 + sizes.length + 1);
      const grade = sizes.length > 1 ? Math.round((p.values[sizes[Math.min(baseIdx + 1, sizes.length - 1)]] - p.values[sizes[baseIdx]]) * 100) / 100 : 0;
      const sizeCells = sizes.map((s, si) => (si === baseIdx ? p.values[s] : { formula: `${baseCol}${r}${si - baseIdx >= 0 ? "+" : "-"}${Math.abs(si - baseIdx)}*${gradeCol}${r}` }));
      return [p.code, p.name_en, p.name_ar, p.how_to_measure_en, ...sizeCells, p.tolerance_cm, grade, p.derivation, p.source, p.confidence, ""];
    });
    table(ws, headers, rows, [7, 34, 34, 44, ...sizes.map(() => 8), 7, 7, 40, 10, 11, 24]);
    const dvCol = colLetter(headers.length);
    for (let i = 0; i < rows.length; i++) {
      ws.getCell(`${dvCol}${firstDataRow + i}`).dataValidation = { type: "list", allowBlank: true, formulae: ['"OK,Adjust,Query"'] };
    }
  }

  // BOM
  {
    const ws = sheet(wb, "BOM", rtl);
    title(ws, "Bill of materials / قائمة المواد");
    table(
      ws,
      ["Ref", "Category", "Item (EN)", "Item (AR)", "Description", "Composition", "gsm", "Width cm", "Placement", "Qty / unit", "Unit", "Colour rule", "Supplier", "Source", "Confidence", "Notes"],
      pack.bom.map((b) => [b.ref, b.category, b.item_en, b.item_ar, b.description_en, b.composition, b.weight_gsm, b.width_cm, `${b.placement_en} / ${b.placement_ar}`, b.qty_per_unit, b.unit, b.colour_rule_en, b.supplier, b.source, b.confidence, b.notes_en]),
      [6, 11, 24, 24, 40, 18, 7, 9, 30, 9, 7, 26, 16, 9, 10, 30],
    );
  }

  // Construction
  {
    const ws = sheet(wb, "Construction", rtl);
    title(ws, "Construction standards and operation sheet / معايير التصنيع وجدول العمليات");
    const s = pack.construction.standards;
    table(
      ws,
      ["Standard", "Value"],
      [
        ["Stitch type", s.stitch_type],
        ["Seam type", s.seam_type],
        ["SPI seaming", s.spi_seam],
        ["SPI topstitch", s.spi_topstitch],
        ["Seam allowance", `${s.seam_allowance_cm} cm`],
        ["Topstitch", `${s.topstitch_rows} row(s) at ${s.topstitch_offset_cm} cm from edge`],
        ["Needle", s.needle],
        ["Thread seaming", s.thread_seaming],
        ["Thread topstitch", s.thread_topstitch],
        ["Interfacing", s.interfacing_en],
        ["Pressing", s.pressing_en],
        ["SAM estimate", pack.construction.sam_estimate_min ? `${pack.construction.sam_estimate_min} min — ${pack.construction.sam_note_en}` : pack.construction.sam_note_en],
      ],
      [22, 110],
    );
    table(
      ws,
      ["Step", "Operation (EN)", "Operation (AR)", "Machine", "Stitch", "SPI", "Notes (EN)", "Notes (AR)"],
      pack.construction.operations.map((o) => [o.step, o.operation_en, o.operation_ar, o.machine, o.stitch, o.spi, o.notes_en, o.notes_ar]),
      [6, 48, 48, 22, 8, 8, 40, 40],
    );
    if (pack.construction.special_notes_en.length) {
      table(ws, ["Special notes"], pack.construction.special_notes_en.map((n) => [n]), [120]);
    }
  }

  // Colorways
  {
    const ws = sheet(wb, "Colorways", rtl);
    title(ws, "Colorways / الألوان", pack.colorway_note_en);
    table(
      ws,
      ["Colorway", "Name (EN)", "Name (AR)", "Component (EN)", "Component (AR)", "Colour", "Pantone TCX", "Hex", "BOM ref", "Needle thread", "Bobbin thread", "Label side"],
      pack.colorways.flatMap((cw) => cw.components.map((c) => [cw.code, cw.name_en, cw.name_ar, c.component_en, c.component_ar, c.colour_name, c.pantone_tcx, c.hex, c.bom_ref, cw.thread_needle, cw.thread_bobbin, cw.label_side_en])),
      [9, 24, 24, 24, 24, 14, 14, 10, 8, 24, 24, 30],
    );
  }

  // Labels, packaging, QC
  {
    const ws = sheet(wb, "Labels_Packaging_QC", rtl);
    title(ws, "Labels / البطاقات");
    table(ws, ["Type", "Placement (EN)", "Placement (AR)", "Content (EN)", "Content (AR)", "Notes"], pack.labels.map((l) => [l.type, l.placement_en, l.placement_ar, l.content_en, l.content_ar, l.notes_en]), [26, 36, 36, 40, 40, 36]);
    title(ws, "Packaging / التعبئة");
    table(ws, ["Method", "Items", "Carton note"], [[`${pack.packaging.method_en}\n${pack.packaging.method_ar}`, pack.packaging.items_en.join("\n"), pack.packaging.carton_note_en]], [60, 60, 40]);
    title(ws, "Quality control / مراقبة الجودة", pack.qc.aql_en);
    table(ws, ["Check (EN)", "Check (AR)"], pack.qc.checks_en.map((c, i) => [c, pack.qc.checks_ar[i] ?? ""]), [70, 70]);
    table(ws, ["Lab / fabric tests"], pack.qc.tests_en.map((t) => [t]), [120]);
  }

  // Consumption
  {
    const ws = sheet(wb, "Consumption", rtl);
    title(ws, "Fabric consumption / استهلاك القماش", pack.consumption.formulas_en.join("  |  "));
    const qtyRow = ws.rowCount + 1;
    ws.addRow(["Run quantity (edit)", pack.consumption.run_quantity ?? 0]);
    ws.getCell(`B${qtyRow}`).font = { bold: true, color: { argb: "FF5F50BC" } };
    ws.addRow([]);
    const start = ws.rowCount + 2;
    table(
      ws,
      ["Colour", "Net area cm² / shell", "Gross area cm²", "Metres per unit", "Grams per unit", "Run total metres"],
      pack.consumption.per_unit.map((c, i) => [c.colour, c.net_area_cm2, c.gross_area_cm2, c.metres_per_unit, c.grams_per_unit, { formula: `D${start + i}*$B$${qtyRow}` }]),
      [18, 20, 18, 16, 16, 18],
    );
    table(ws, ["Parameter", "Value"], [["Fabric width cm", pack.consumption.fabric_width_cm], ["Usable width cm", pack.consumption.usable_width_cm], ["Marker efficiency", pack.consumption.marker_efficiency], ["Shrinkage allowance %", pack.consumption.shrinkage_allowance_pct]], [26, 14]);
    if (pack.pattern_pieces.length) {
      table(ws, ["Pattern piece (EN)", "Pattern piece (AR)", "Qty / shell", "Qty total", `Cut dimensions (${pack.header.base_size})`, "Notes"], pack.pattern_pieces.map((p) => [p.name_en, p.name_ar, p.qty_per_shell, p.qty_total, p.cut_dimensions_base_en, p.notes_en]), [28, 28, 10, 10, 44, 60]);
    }
  }

  // Assumptions & questions
  {
    const ws = sheet(wb, "Assumptions", rtl);
    title(ws, "Assumptions / الافتراضات");
    table(ws, ["Impact", "Assumption (EN)", "Assumption (AR)"], pack.assumptions.map((a) => [a.impact, a.text_en, a.text_ar]), [10, 70, 70]);
    title(ws, "Questions for the factory / أسئلة للمصنع");
    table(ws, ["Question (EN)", "Question (AR)", "Factory answer"], pack.questions_for_factory.map((q) => [q.text_en, q.text_ar, ""]), [60, 60, 40]);
  }

  // Readiness + revision log
  {
    const ws = sheet(wb, "Readiness_Revisions", rtl);
    title(ws, `Factory readiness ${pack.readiness.score}/100`);
    table(ws, ["Check", "Pass", "Note"], pack.readiness.checks.map((c) => [c.item_en, c.pass ? "✔" : "✘", c.note_en]), [60, 8, 40]);
    title(ws, "Revision log");
    table(ws, ["Version", "Date", "Author", "Change"], pack.revision_log.map((r) => [r.version, r.date, r.author, r.change_en]), [10, 14, 22, 80]);
  }

  const out = await wb.xlsx.writeBuffer();
  return Buffer.from(out as ArrayBuffer);
}

function colLetter(n: number): string {
  let s = "";
  while (n > 0) {
    const m = (n - 1) % 26;
    s = String.fromCharCode(65 + m) + s;
    n = Math.floor((n - 1) / 26);
  }
  return s;
}
