/**
 * Bucket hat rulebook. Industry defaults and formulas for a reversible,
 * unlined, two-shell cotton twill bucket hat. Values are finished measurements
 * in cm unless stated. Everything graded is derived from head circumference.
 *
 * Reconciled from three independent technologist passes plus web verification
 * (docs/research/rulebook-reconciled.json). Key resolutions: 30° cone brim,
 * labels sewn flat before side seams, no topstitch on internal seams, SA trimmed
 * to 7 mm so the 6 mm brim row catches it, full-round stitch-in-ditch.
 */

export const BUCKET_HAT_RULEBOOK = {
  template_id: "bucket_hat",
  base_size: "M",
  sizes: [
    { code: "S", label_en: "Small", label_ar: "صغير", head_girth_range_cm: "55–56", finished_inner_circumference_cm: 57 },
    { code: "M", label_en: "Medium", label_ar: "متوسط", head_girth_range_cm: "57–58", finished_inner_circumference_cm: 59 },
    { code: "L", label_en: "Large", label_ar: "كبير", head_girth_range_cm: "59–60", finished_inner_circumference_cm: 61 },
  ],
  defaults: {
    ease_cm: 1.0,
    circumference_grade_cm: 2.0,
    crown_height_cm: 9.0,
    crown_height_grade_cm: 0.5,
    brim_width_cm: 6.5,
    brim_width_grade_cm: 0.0,
    brim_drop_deg: 30,
    band_taper_cm: 2.5,
    topstitch_offset_cm: 0.6,
    topstitch_rows: 1,
    seam_allowance_cm: 1.0,
    bagout_trim_cm: 0.7,
    turning_gap_cm: 8,
    label_below_tip_seam_cm: 1.5,
  },
  tolerances_cm: {
    A: 1.0,
    B: 0.5,
    C: 0.3,
    D: 0.3,
    E: 0.7,
    F: 1.5,
    G: 0.1,
    H: 1.0,
    J: 0.3,
    W: 1.0,
  },
  pom_names: {
    A: { en: "Inner head circumference at crown/brim seam", ar: "محيط الرأس الداخلي عند خط وصل التاج بالحافة", how_en: "Measure inside the hat along the crown-to-brim seam, full circumference, hat laid flat and relaxed.", how_ar: "يقاس من داخل القبعة على طول خط وصل التاج بالحافة، المحيط كاملاً، والقبعة مفرودة ومرتخية." },
    B: { en: "Crown side height (band), tip seam to crown/brim seam", ar: "ارتفاع جانب التاج (الحزام) من خط القمة إلى خط الحافة", how_en: "At the side seam, from the tip seam down to the crown/brim seam.", how_ar: "عند خط الجنب، من خط القمة نزولاً إلى خط وصل التاج بالحافة." },
    C: { en: "Brim width, seam to finished edge", ar: "عرض الحافة من خط الوصل إلى الحافة النهائية", how_en: "At centre front, along the brim surface from the crown/brim seam to the finished edge.", how_ar: "عند منتصف الأمام، على سطح الحافة من خط وصل التاج إلى الحافة النهائية." },
    D: { en: "Crown tip diameter, seam to seam", ar: "قطر قمة التاج من خط إلى خط", how_en: "Across the top circle, seam line to seam line, through the centre.", how_ar: "عبر الدائرة العلوية من خط الوصل إلى خط الوصل مروراً بالمركز." },
    E: { en: "Total height flat, tip seam to brim edge at side", ar: "الارتفاع الكلي مفروداً من خط القمة إلى حافة الحافة عند الجنب", how_en: "Hat laid flat, brim extended, from the tip seam to the brim edge at the side seam. Check POM = B + C.", how_ar: "القبعة مفرودة والحافة ممدودة، من خط القمة إلى حافة الحافة عند خط الجنب. نقطة تحقق = B + C." },
    F: { en: "Brim outer edge circumference", ar: "المحيط الخارجي لحافة الحافة", how_en: "Around the finished brim edge with the brim in its natural 30° drop.", how_ar: "حول الحافة النهائية للحافة في وضعها الطبيعي المائل 30 درجة." },
    G: { en: "Brim topstitch distance from edge", ar: "بعد الحياكة الزخرفية عن حافة الحافة", how_en: "From the finished brim edge to the single topstitch row, checked at CF, CB and both sides.", how_ar: "من حافة الحافة النهائية إلى صف الحياكة الزخرفية، يُفحص عند الأمام والخلف والجانبين." },
    H: { en: "Crown tip circumference at seam", ar: "محيط قمة التاج عند خط الوصل", how_en: "Along the tip seam line, full circumference.", how_ar: "على طول خط وصل القمة، المحيط كاملاً." },
    J: { en: "Brand label position below tip seam, CB", ar: "موضع العلامة التجارية أسفل خط القمة عند منتصف الخلف", how_en: "On the designated outer shell at CB, from the tip seam to the top edge of the brand label.", how_ar: "على الجسم الخارجي المحدد عند منتصف الخلف، من خط القمة إلى الحافة العلوية للعلامة." },
    W: { en: "Full width across brim on head form, side to side", ar: "العرض الكلي عبر الحافة على القالب من جنب إلى جنب", how_en: "On a head form, straight across the brim edge through the centre. Check POM = A/π + 2·C·cos30°.", how_ar: "على قالب الرأس، بخط مستقيم عبر حافة الحافة مروراً بالمركز. نقطة تحقق = A/π + 2·C·cos30°." },
  },
  fabric: {
    composition: "100% cotton",
    weave: "3/1 right-hand twill, face side out on both shells; construction per mill to reach the target weight (typically 16s–20s Ne warp × 12s–16s Ne weft)",
    gsm: 280,
    gsm_tolerance_pct: 5,
    width_cm: 150,
    usable_width_cm: 147,
    shrinkage_max_pct: 3,
    pre_treatment_en: "Sanforized / pre-shrunk, piece or reactive dyed; identical quality in both colours; factory to confirm residual shrinkage ≤ 3% on each colour lot before cutting; relax 24 h before laying",
    marker_efficiency: 0.7,
    shrinkage_allowance_pct: 3,
    buying_allowance_pct: 10,
  },
  thread: {
    seaming: { spec: "Core-spun polyester, Tex 30 (Tkt 100)", needle: "DBx1 Nm 80/12 R point (Nm 90/14 only if skip stitches occur at seam crossings)" },
    topstitch: { spec: "Core-spun polyester, Tex 40 (Tkt 75)", needle: "DBx1 Nm 90/14 R point" },
    colour_rule_en: "Single-shell seams: DTM the shell being sewn, needle and bobbin. Every seam that passes through both shells (bag-out, brim topstitch, stitch-in-ditch): needle thread DTM the face up (khaki), bobbin DTM the face down (black), balanced so no bobbin colour shows on either face",
  },
  stitching: {
    stitch_type: "301 lockstitch (ISO 4915) for every operation; no chainstitch, no overlock (every raw edge is enclosed between the shells)",
    seam_type: "SSa-1 plain superimposed seams, 1.0 cm SA; brim outer edge bagged (runstitch, trim to 0.7 cm, turn, single topstitch) per ISO 4916",
    spi_seam: "10–12 SPI (12–14 stitches / 3 cm)",
    spi_topstitch: "8–9 SPI",
    interfacing_en: "None by default (soft, packable brim). If a firmer brim is required, fuse BOTH brim sets identically with 50–70 gsm woven fusible, never one shell only",
    pressing_en: "Press side seams open on each shell; press bag-out seam exactly to the edge before topstitching; final steam on a head form",
  },
  pattern_pieces: [
    { name_en: "Crown tip (top circle)", name_ar: "قمة التاج (الدائرة العلوية)", qty_per_shell: 1, notes_en: "Cut diameter = D + 2 × SA; grain CF–CB; notch at CF, CB and both sides." },
    { name_en: "Side band (crown) panel", name_ar: "لوح الحزام الجانبي (التاج)", qty_per_shell: 2, notes_en: "Bottom edge = A/2 + 2 × SA, top edge = H/2 + 2 × SA, height = B + 2 × SA; warp along the circumference; seams at both sides." },
    { name_en: "Brim half (cone sector)", name_ar: "نصف الحافة (قطاع مخروطي)", qty_per_shell: 2, notes_en: "Developed 30° cone: inner radius = A/(2π·cos30°) − SA, outer radius = inner + C + 2 × SA, sector 155.9° per half; seams at both sides aligned with band seams; grain on the centre radius." },
  ],
  operations: [
    { step: 1, operation_en: "Cut all pieces per marker, one marker file for both colours with identical ply counts; 2 complete shells per hat (khaki set + black set); check shade continuity per lot", operation_ar: "قص جميع القطع حسب الماركر، ماركر واحد للونين وبنفس عدد الطبقات؛ جسمان كاملان لكل قبعة (طقم كاكي + طقم أسود)؛ التأكد من تطابق درجة اللون لكل دفعة", machine: "Cutting table / straight knife", stitch: "—", spi: "—", notes_en: "Lay ≤ 50 plies after 24 h relaxation; notch CF/CB/sides on tip, band and brim; keep brim halves in matched pairs" },
    { step: 2, operation_en: "Sew brand label flat on the designated outer-shell band panel at CB, 1.5 cm below the tip seam line; sew care/content label on the reverse-shell band panel at CB (flat, before side seams)", operation_ar: "تثبيت العلامة التجارية مسطحة على لوح الحزام للجسم الخارجي المحدد عند منتصف الخلف، 1.5 سم أسفل خط القمة؛ وتثبيت بطاقة العناية على لوح الحزام للجسم الداخلي (مسطحاً قبل خياطة الجنب)", machine: "Label attach / 1-needle lockstitch", stitch: "301", spi: "10–12", notes_en: "Which shell carries the brand label is the only difference between CW1 and CW2" },
    { step: 3, operation_en: "Join side band halves at both side seams (each shell); press seams open", operation_ar: "وصل نصفي الحزام الجانبي عند خطي الجنب (لكل جسم)؛ كي الخياطة مفتوحة", machine: "1-needle lockstitch (DBx1)", stitch: "301", spi: "10–12", notes_en: "1 cm SA; backtack 3 stitches; no topstitch on internal seams" },
    { step: 4, operation_en: "Attach crown tip to band matching CF/CB/side notches (each shell); zero ease, no pleats", operation_ar: "تركيب قمة التاج بالحزام مع مطابقة علامات الأمام والخلف والجانبين (لكل جسم)؛ بدون تسهيل أو كسرات", machine: "1-needle lockstitch, cylinder bed preferred", stitch: "301", spi: "10–12", notes_en: "1 cm SA; SA toward band; tip seam is not topstitched (enclosed between nested crowns)" },
    { step: 5, operation_en: "Join brim halves at both side seams (each shell); press open", operation_ar: "وصل نصفي الحافة عند خطي الجنب (لكل جسم)؛ كي الخياطة مفتوحة", machine: "1-needle lockstitch", stitch: "301", spi: "10–12", notes_en: "1 cm SA; seams must align with band side seams" },
    { step: 6, operation_en: "Clip brim inner curve SA every 2 cm; attach brim inner edge to crown/band lower edge (each shell), matching side seams and notches", operation_ar: "قص شقوق في بدل خياطة المنحنى الداخلي للحافة كل 2 سم؛ تركيب الحافة الداخلية بالحافة السفلية للتاج (لكل جسم) مع مطابقة خطوط الجنب والعلامات", machine: "1-needle lockstitch, cylinder bed", stitch: "301", spi: "10–12", notes_en: "1 cm SA pressed toward the crown on both shells" },
    { step: 7, operation_en: "Nest the two shells right sides together, all side seams stacked; runstitch around the brim outer edge leaving an 8 cm gap at CB", operation_ar: "تعشيق الجسمين وجهاً لوجه مع تطابق خطوط الجنب؛ خياطة حول الحافة الخارجية للحافة مع ترك فتحة 8 سم عند منتصف الخلف", machine: "1-needle lockstitch", stitch: "301", spi: "10–12", notes_en: "1 cm SA; needle DTM khaki, bobbin DTM black" },
    { step: 8, operation_en: "Trim bag-out SA to 0.7 cm; snip at the gap ends; turn through the gap; work the seam exactly to the edge; press", operation_ar: "تقليم بدل الخياطة إلى 0.7 سم؛ قص عند طرفي الفتحة؛ قلب القبعة عبر الفتحة؛ ضبط الخياطة على الحافة تماماً؛ كي", machine: "Trimming / turning / pressing", stitch: "—", spi: "—", notes_en: "0.7 cm keeps the SA inside the 0.6 cm topstitch so the row catches and flattens it; no roll to either face" },
    { step: 9, operation_en: "Single-row brim topstitch 0.6 cm from the edge, full round, closing the gap; needle DTM khaki, bobbin DTM black; overlap 1.5 cm at CB", operation_ar: "حياكة زخرفية صف واحد على بعد 0.6 سم من حافة الحافة دورة كاملة مع إغلاق الفتحة؛ خيط الإبرة كاكي والمكوك أسود؛ تداخل 1.5 سم عند منتصف الخلف", machine: "1-needle lockstitch (or brim stitcher)", stitch: "301", spi: "8–9", notes_en: "The only visible topstitch on the product; check G = 0.6 ± 0.1 cm at four points" },
    { step: 10, operation_en: "Stitch-in-ditch full round in the crown/brim seam through both shells, side seams stacked", operation_ar: "غرزة في خط الوصل دورة كاملة في خط وصل التاج بالحافة عبر الجسمين مع تطابق خطوط الجنب", machine: "1-needle lockstitch", stitch: "301", spi: "10–12", notes_en: "Invisible on both faces; stops the crowns ballooning apart when reversed; needle khaki, bobbin black" },
    { step: 11, operation_en: "Trim threads; final steam press on head form; inspect both faces and measure against the POM chart", operation_ar: "قص الخيوط؛ الكي النهائي بالبخار على القالب؛ فحص الوجهين والقياس مقابل جدول القياسات", machine: "Finishing", stitch: "—", spi: "—", notes_en: "Check no bobbin colour shows on the wrong face; check A, B, C, G" },
    { step: 12, operation_en: "Attach hangtag by string through the brand label; fold brim up; polybag with the designated outer face showing; carton per packing spec", operation_ar: "تعليق البطاقة بخيط عبر العلامة التجارية؛ طي الحافة لأعلى؛ التعبئة في كيس بحيث يظهر الوجه الخارجي المحدد؛ الكرتون حسب مواصفة التعبئة", machine: "Packing", stitch: "—", spi: "—", notes_en: "No tag-gun holes on a product with two outer faces" },
  ],
  sam_estimate_min: 13.5,
  sam_note_en: "Operation-based estimate (no published headwear SAM): ≈13.5 sewing/pressing minutes per hat (≈4.1 per shell × 2, labels 0.8, bag-out/turn/topstitch/ditch 4.5) plus ≈2.5 finishing and ≈1.5 cutting/bundling ≈ 17.5 min total. Colorway does not change SAM. Confirm with a first-bundle time study.",
  labels: [
    { type: "Main woven brand label", placement_en: "Sewn flat on the designated outer shell, band at CB, 1.5 cm below the tip seam (POM J)", placement_ar: "مخيطة مسطحة على الجسم الخارجي المحدد، الحزام عند منتصف الخلف، 1.5 سم أسفل خط القمة", content_en: "Brand logo", content_ar: "شعار العلامة التجارية", notes_en: "Which shell carries this label is what defines the colorway; sew before the side seams" },
    { type: "Care / content / origin label", placement_en: "Reverse shell, band at CB, 1.5 cm below the tip seam", placement_ar: "الجسم الداخلي، الحزام عند منتصف الخلف، 1.5 سم أسفل خط القمة", content_en: "100% Cotton / Made in Egypt / manufacturer name / size with cm range / ISO 3758 care symbols: wash 30°C, do not bleach, do not tumble dry, iron medium, do not dry clean", content_ar: "100% قطن / صنع في مصر / اسم المصنع / المقاس مع نطاق السنتيمتر / رموز العناية ISO 3758: غسيل 30 درجة، لا تبييض، لا تجفيف بالمجفف، كي متوسط، لا تنظيف جاف", notes_en: "Arabic and English text; obligatory under ES 7266-3/2023 for the Egyptian market; printed satin, black on white ground" },
    { type: "Size label", placement_en: "Combined with care label", placement_ar: "مدمجة مع بطاقة العناية", content_en: "S (55–56 cm) / M (57–58 cm) / L (59–60 cm)", content_ar: "S (55–56 سم) / M (57–58 سم) / L (59–60 سم)", notes_en: "Alpha size plus head-girth range per EN 13402 practice" },
    { type: "Hangtag", placement_en: "String through the brand label; no tag-gun holes", placement_ar: "بخيط عبر العلامة التجارية؛ بدون ثقوب مسدس التعليق", content_en: "Brand, style, colorway name, size, 'reversible' icon", content_ar: "العلامة التجارية، الموديل، اسم اللون، المقاس، رمز الوجهين", notes_en: "The hangtag and the label side are what tell CW1 from CW2" },
  ],
  packaging: {
    method_en: "Fold brim up around the crown, one hat per polybag with the designated outer face showing; 12 per inner pack by size and colorway; export carton 48 pcs (4 × 12) with size ratio per order",
    method_ar: "طي الحافة لأعلى حول التاج، قبعة واحدة في كل كيس بحيث يظهر الوجه الخارجي المحدد؛ 12 قطعة في العبوة الداخلية حسب المقاس واللون؛ كرتون تصدير 48 قطعة",
    items_en: ["Polybag with suffocation warning, 25 × 30 cm, recycled LDPE", "Size sticker on polybag", "Inner pack of 12, single size, single colorway", "Master carton 48 pcs, 5-ply, labelled style / colorway / size / qty"],
    carton_note_en: "Carton dimensions TBC by factory after PP sample; keep cartons under 15 kg",
  },
  qc: {
    aql_en: "ISO 2859-1 General Inspection Level II, AQL 2.5 major / 4.0 minor",
    checks_en: [
      "Measure 10 pcs per size against the POM chart; inner circumference within ±1.0 cm",
      "Brim topstitch 6 ± 1 mm from edge at CF, CB and both sides, continuous, no visible join",
      "No bobbin colour visible on the wrong face; no shading between panels of the same colour",
      "Brim edge seam sits on the edge, no roll to either face; brim drops evenly all round",
      "Tip seam smooth with no pleats; side seams aligned across band and brim on both shells",
      "Labels on the correct shell per colorway, straight, at 1.5 cm below the tip seam",
      "Both faces free of stains, marks, needle holes and loose threads",
    ],
    checks_ar: [
      "قياس 10 قطع لكل مقاس مقابل جدول القياسات؛ المحيط الداخلي ضمن ±1.0 سم",
      "الحياكة الزخرفية للحافة على بعد 6 ± 1 مم عند الأمام والخلف والجانبين ومستمرة دون وصلة ظاهرة",
      "عدم ظهور لون خيط المكوك على الوجه الخطأ؛ عدم وجود اختلاف درجة لون بين أجزاء نفس اللون",
      "خياطة حافة الحافة تقع على الحافة تماماً دون التفاف؛ الحافة تنسدل بالتساوي حول القبعة",
      "خط القمة أملس بدون كسرات؛ خطوط الجنب متطابقة بين الحزام والحافة في الجسمين",
      "البطاقات على الجسم الصحيح حسب اللون ومستقيمة على بعد 1.5 سم أسفل خط القمة",
      "الوجهان خاليان من البقع والعلامات وثقوب الإبرة والخيوط السائبة",
    ],
    tests_en: [
      "Fabric weight 280 gsm ± 5% (ISO 3801) per colour lot",
      "Dimensional stability to washing ≤ 3% (ISO 6330 / ISO 5077), both lots tested together",
      "Colour fastness to washing grade 4 min (ISO 105-C06); black staining onto khaki is the critical result",
      "Colour fastness to rubbing dry 4 / wet 3 min (ISO 105-X12)",
      "Seam strength spot check on the brim bag-out seam",
    ],
  },
  colour_refs: [
    { name: "Khaki", pantone_tcx: "16-0726 TCX", hex: "#A39264" },
    { name: "Jet Black", pantone_tcx: "19-0303 TCX", hex: "#2D2C2F" },
    { name: "Bright White", pantone_tcx: "11-0601 TCX", hex: "#F4F5F0" },
  ],
  reversible_notes_en: [
    "Two complete shells, no separate lining, no sweatband; every seam allowance is trapped between the shells so both faces are clean; no overlock anywhere",
    "'Khaki outer / black reverse' and 'black outer / khaki reverse' are the same physical hat: same pattern, shells, threads, consumption and SAM. The colorways differ only in which shell carries the brand label, the face shown in packaging and the hangtag. Order as one style with two colorway codes so fabric, cutting and sewing are pooled",
    "Ventilation eyelets omitted by default; if required, use 4 embroidered eyelets per shell at 3.5 cm above the brim seam, 2 per side",
    "No stiffener: with two layers of 280 gsm twill and a single topstitch row the brim is soft and packable; a stiffer brim needs fusible on BOTH brim sets",
    "One marker file with identical ply counts on both colour lays: a shortfall in either colour stops the run because every hat needs one shell of each",
  ],
} as const;

export type BucketHatRulebook = typeof BUCKET_HAT_RULEBOOK;
